dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: a5L51Q/5tM8wTkJH5sSl1M1yTXv25P1aSiVKIUaQIIXzOa+qUYGsesfopL5aFVw87rExMMhsN3yCEBNkVi+n4TynyjfFsgCNW+NcLmkQkzpyfn24JRKQf8vsvUl8AVEJt/4dU2mqSp5iwIrapMQMP44tvgjaMLoQ4HGrGmz9q1of01TDM/t9BXzPGkwxbbCXWx+vLkIxs/iMXlTYMo1zOue+14FoJks4rKJKIbIypPK4BpFhN2PgN+EWcl6FZcrR0vDYEEdTtnx/ka3s0AA46Xf8NtrPlNRUQbPcuq27NAfSMDSC+aUvBU17974AsclwFkTM1zwVjghZtMnW/8Dq3g3J4Ugs5xlu2rBnteUMJC/tqTFCU0XfqTDGcNCdsfEC8sWPHsr0QPwC7YVwqki31+aPc1Ps2vk8LBpESAn7bDiA7fOr/H58EREvn5Pp8M4CSxkN/ptolqNmy7xXWw5j1Vf8fDJeBUHi7dZAffxmPIPC8RnGOItfV2TQgDO0xMs4IPhplt1UWYwJev09Xq8Svso2iwybbvi42AAwrYTxx8q7SEjAz1+nX288Ush/QlX36deRqLpksJ9BiRYNJmrgCSPoL+HGNQK9BXrYowTrDX9nO01Jg34u7qsg4sXFMzsOOmZ2sN5bLE+vQr8X0mbtDPMsUrN5dkWmkajJmrQDDX4=
