version: '3.3'
services:
  source:
    image: ${USERNAME}/source
    volumes:
      - source_app:/reddit/app
  ui:
    volumes:
      - source_app:/reddit/app
    command: "puma --debug -w 2"
    depends_on:
      - source
  post:
    volumes:
      - source_app:/reddit/app
    depends_on:
      - source
  comment:
    volumes:
      - source_app:/reddit/app
    depends_on:
      - source
    command: "puma --debug -w 2"
volumes:
  source_app:
