version: '3.3'
services:
  source:
    image: ${USERNAME}/source
    volumes:
      - source_app:/reddit/app
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
    depends_on:
      - source
  ui:
    image: ${USERNAME}/ui:${UI_V}
    volumes:
      - source_app:/reddit/app
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    command: "puma --debug -w 2"
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
    depends_on:
      - source
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USERNAME}/post:${POST_V}
    volumes:
      - source_app:/reddit/app
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}      
    networks:
      - front_net
      - back_net
    depends_on:
      - source
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${COMMENT_V}
    volumes:
      - source_app:/reddit/app
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}      
    command: "puma --debug -w 2"
    networks:
      - front_net
      - back_net
    depends_on:
      - source

volumes:
  post_db:
  source_app:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
