version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin:2.11.8
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net      
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - back_net
  elasticsearch:
    image: elasticsearch:6.5.4
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    image: kibana:6.5.4
    ports:
      - "5601:5601"
    networks:
      - back_net


networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24  
