runner:
  restart: always
  image: gitlab/gitlab-runner:latest
  volumes:
    - '/srv/gitlab-runner-1/config:/etc/gitlab-runner'
    - '/var/run/docker.sock:/var/run/docker.sock'

runner-1-register:
  image: 'gitlab/gitlab-runner:latest'
  restart: "no"
  volumes:
    - '/srv/gitlab-runner-1/config:/etc/gitlab-runner'
  command:
    - register
    - --non-interactive
    - --url=<IP>
    - --registration-token=<token>
    - --tag-list=linux
    - --description=my-runner
    - --executor=docker
    - --docker-image=alpine:3.8
    - --run-untagged
    - --locked=false
